feat: add `SingleLineCommentStyle` type to variables and params.
- Changed various docblock comments.

- Changed Map key typings to the union type of `"customSupportedLanguages" | "supportedLanguages"` instead of just `string` in the class properties `singleLineBlocksMap` and `multiLineBlocksMap`.

This is to be more verbose for what keys the Map can have. Since it's only these 2 keys, it makes sense to just use them as a union type. It also aids in vscode intellisense.

- Changed typings to use `SingleLineCommentStyle` type instead of just `string` for:

    - `singleLineBlocksMap` class property inner Map value.

    - `getSingleLineLanguages` method return type.

    - `tempMap` variable in `setSingleLineCommentLanguageDefinitions` method.

    - Docblock types.

    - `singleLineStyle` param of `setLanguageConfiguration` method.

    - `style` variable in `handleSingleLineBlock` method.

- Added new `ExtraSingleLineCommentStyles` type to define all the extra single-line comment styles like `///` and `##`.

This is needed to prevent ts errors like: "error TS2322: Type '";;"' is not assignable to type 'SingleLineCommentStyle'."

This was because changing the style types to use `SingleLineCommentStyle`, it affected the `handleSingleLineBlock` method usage of setting the extra styles directly on the `style` variable. Thus ts would rightly error that we're not allowed to set the style to anything other than specified in the union type.

This new type is the union of all the extra styles, and we just use it on the `style` variable as a union of both `SingleLineCommentStyle` and `ExtraSingleLineCommentStyles` to ensure the extra styles are allowed.